`assert` 模块提供了一组断言函数，用于验证不变量

## 严格的断言模式

在严格的断言模式中，对象的错误消息会显示差异。 在传统的断言模式中，对象的错误消息会显示对象（通常是截断的）

```js
//index.js
const assert = require('assert').strict
assert.deepStrictEqual([[[1, 2, 3]], 4, 5], [[[1, 2, '3']], 4, 5]) //#1
assert.deepStrictEqual([[[1, 2, 3]], 4, 5], [[[1, 2, 3]], 4, 5]) //#2
//执行
node index.js   //#1  error  3!=='3' ; #2 ok
```

## 传统的断言模式

只要有可能，使用严格的断言模式，否则抽象的相等性比较可能会导致意外的结果。

```js
const assert = require('assert');
// 注意：这不会抛出 AssertionError！
assert.deepEqual(/a/gi, new Date());
```

## assert.AssertionError 类

表明断言的失败。 `assert` 模块抛出的所有错误都是 `AssertionError` 类的实例。

# new assert.AssertionError(options)

- `options` <Object>
    - `message` <String>如果提供，则将错误消息设置为此值。
    - `actual`<any> 错误实例上的 `actual` 属性将包含此值。
    - `expected` <any> 错误实例上的 `expected` 属性将包含此值。
    - `operator` <string> 错误实例上的 `operator` 属性将包含此值。
    - `stackStartFn`<Function> 如果提供，则生成的堆栈跟踪将移除所有帧直到提供的函数。

`Error` 的子类，表明断言的失败。

所有实例都包含内置的 `Error` 属性（`message` 和 `name`）以及：

- `actual` <any>设置方法的 `actual` 参数，例如 [`assert.strictEqual()`](http://nodejs.cn/s/bjx9Nb)。
- `expected` <any> 设置方法的 `expected` 参数，例如 [`assert.strictEqual()`](http://nodejs.cn/s/bjx9Nb)。
- `generatedMessage` <boolean> 表明消息是否是自动生成的。
- `code`<string> 始终设置为字符串 `ERR_ASSERTION` 以表明错误实际上是断言错误。
- `operator` <string> 设置为传入的运算符值。

```js
const assert = require('assert');

// 生成 AssertionError 以便稍后比较错误的消息：
const { message } = new assert.AssertionError({
  actual: 1,
  expected: 2,
  operator: 'strictEqual'
});

// 验证错误的输出：
try {
  assert.strictEqual(1, 2);
} catch (err) {
  assert(err instanceof assert.AssertionError);
  assert.strictEqual(err.message, message);
  assert.strictEqual(err.name, 'AssertionError');
  assert.strictEqual(err.actual, 1);
  assert.strictEqual(err.expected, 2);
  assert.strictEqual(err.code, 'ERR_ASSERTION');
  assert.strictEqual(err.operator, 'strictEqual');
  assert.strictEqual(err.generatedMessage, true);
}
```

# assert(value[, message])

- `value` <any> 检查是否为真的输入。
- `message` <string> | <Error>

[`assert.ok()`](http://nodejs.cn/s/xzCLSQ) 的别名。

# assert.deepStrictEqual(actual, expected[, message])

- `actual`<any>
- `expected` <any>
- `message` <string> | <Error>

测试 `actual` 参数和 `expected` 参数之间的深度相等。 深度相等意味着子对象的可枚举的自身属性也通过以下规则进行递归计算。

# 比较运算的详细说明

- 使用 [SameValue比较](http://nodejs.cn/s/25ULs2)（使用 [`Object.is()`](http://nodejs.cn/s/fQqJVi)）来比较原始值。
- 对象的[类型标签](http://nodejs.cn/s/NVhBn1)应该相同。
- 使用[严格相等比较](http://nodejs.cn/s/jFa5Tv)来比较对象的[原型](http://nodejs.cn/s/yzA3TL)。
- 只考虑[可枚举的自身属性](http://nodejs.cn/s/hTNJUJ)。
- 始终比较 [`Error`](http://nodejs.cn/s/FLTm19) 的名称和消息，即使这些不是可枚举的属性。
- 可枚举的自身 [`Symbol`](http://nodejs.cn/s/SyrFMg) 属性也会比较。
- [对象封装器](http://nodejs.cn/s/hem2hq)作为对象和解封装后的值都进行比较。
- `Object` 属性的比较是无序的。
- [`Map`](http://nodejs.cn/s/EnuJtG) 键名与 [`Set`](http://nodejs.cn/s/yej4PC) 子项的比较是无序的。
- 当两边的值不相同或遇到循环引用时，递归停止。
- [`WeakMap`](http://nodejs.cn/s/JkfoVY) 和 [`WeakSet`](http://nodejs.cn/s/gsMyy2) 的比较不依赖于它们的值。请参见下文了解更多详情

```js
const assert = require('assert').strict;

// 失败，因为 1 !== '1'。
assert.deepStrictEqual({ a: 1 }, { a: '1' });
// AssertionError: Expected inputs to be strictly deep-equal:
// + actual - expected
//
//   {
// +   a: 1
// -   a: '1'
//   }

// 以下对象没有自身属性。
const date = new Date();
const object = {};
const fakeDate = {};
Object.setPrototypeOf(fakeDate, Date.prototype);

// 原型不同：
assert.deepStrictEqual(object, fakeDate);
// AssertionError: Expected inputs to be strictly deep-equal:
// + actual - expected
//
// + {}
// - Date {}

// 类型标签不同：
assert.deepStrictEqual(date, fakeDate);
// AssertionError: Expected inputs to be strictly deep-equal:
// + actual - expected
//
// + 2018-04-26T00:49:08.604Z
// - Date {}

assert.deepStrictEqual(NaN, NaN);
// 通过，因为使用 SameValue 比较。

// 解封装后的数字不同：
assert.deepStrictEqual(new Number(1), new Number(2));
// AssertionError: Expected inputs to be strictly deep-equal:
// + actual - expected
//
// + [Number: 1]
// - [Number: 2]

assert.deepStrictEqual(new String('foo'), Object('foo'));
// 通过，因为对象与解封装后的字符串都是相同的。

assert.deepStrictEqual(-0, -0);
// 通过。

// 使用 SameValue 比较的零不同：
assert.deepStrictEqual(0, -0);
// AssertionError: Expected inputs to be strictly deep-equal:
// + actual - expected
//
// + 0
// - -0

const symbol1 = Symbol();
const symbol2 = Symbol();
assert.deepStrictEqual({ [symbol1]: 1 }, { [symbol1]: 1 });
// 通过，因为在两个对象上的 symbol 相同。
assert.deepStrictEqual({ [symbol1]: 1 }, { [symbol2]: 1 });
// AssertionError [ERR_ASSERTION]: Inputs identical but not reference equal:
//
// {
//   [Symbol()]: 1
// }

const weakMap1 = new WeakMap();
const weakMap2 = new WeakMap([[{}, {}]]);
const weakMap3 = new WeakMap();
weakMap3.unequal = true;

assert.deepStrictEqual(weakMap1, weakMap2);
// 通过，因为无法比较条目。

// 失败，因为 weakMap3 有一个 weakMap1 不包含的属性：
assert.deepStrictEqual(weakMap1, weakMap3);
// AssertionError: Expected inputs to be strictly deep-equal:
// + actual - expected
//
//   WeakMap {
// +   [items unknown]
// -   [items unknown],
// -   unequal: true
//   }
```

## Object.is()

与===行为基本一致，但有不同之处

```js
+0===-0//true
NaN===NaN//false
Object.is(+0,-0);//false
Object.is(NaN,NaN);//true
```

# assert.doesNotReject(asyncFn[, error],[, message])

- `asyncFn` <Function> | <Promise>
- `error` <RegExp> | <Funciton>
- `message` <string>

等待 `asyncFn` Promise，或者，如果 `asyncFn` 是一个函数，则立即调用该函数并等待返回的 Promise 完成。 然后它将检查 Promise 是否被拒绝。

如果 `asyncFn` 是一个函数并且它同步抛出一个错误，则 `assert.doesNotReject()` 将返回一个带有该错误的被拒绝的 `Promise`。 如果函数未返回 Promise，则 `assert.doesNotReject()` 将返回一个被拒绝的 `Promise`，其中包含 [`ERR_INVALID_RETURN_VALUE`](http://nodejs.cn/s/zKCD5R) 错误。 在这两种情况下都会跳过错误处理函数。

使用 `assert.doesNotReject()` 实际上没有用处，因为捕获拒绝然后再次拒绝它几乎没有什么好处。 应该考虑在不应拒绝的特定代码路径旁边添加注释，并尽可能保留错误消息。

如果指定，则 `error` 可以是 [`Class`](http://nodejs.cn/s/5wDLcp)、[`RegExp`](http://nodejs.cn/s/tbQJCP) 或验证函数。 有关更多详细信息，请参见 [`assert.throws()`](http://nodejs.cn/s/sGRMSp)。

除了等待的异步性质之外，完成行为与 [`assert.doesNotThrow()`](http://nodejs.cn/s/mm4aoA) 完全相同。

```js
(async () => {
  await assert.doesNotReject(
    async () => {
      throw new TypeError('错误值');
    },
    SyntaxError
  );
})();
assert.doesNotReject(Promise.reject(new TypeError('错误值')))
  .then(() => {
    // ...
  });
```

# assert.doesNotThrow(fn[, error],[, message])

- `fn`<Function>
- `error` <RegExp> | <Function>
- `message` <string>

断言 `fn` 函数不会抛出错误。

使用 `assert.doesNotThrow()` 实际上没有用处，因为捕获错误然后重新抛出它没有任何好处。 应该考虑在不应抛出错误的特定代码路径旁边添加注释，并尽可能保留错误消息。

# assert.fail([message])

`message` <string> | <Error>  默认值  'Failed'

用提供的错误消息或默认错误消息抛出 [`AssertionError`](http://nodejs.cn/s/6wNomq)。 如果 `message` 参数是 [`Error`](http://nodejs.cn/s/FLTm19) 的实例，则它将被抛出而不是 [`AssertionError`](http://nodejs.cn/s/6wNomq)。

```js
const assert = require('assert').strict;

assert.fail();
// AssertionError [ERR_ASSERTION]: Failed

assert.fail('失败');
// AssertionError [ERR_ASSERTION]: 失败

assert.fail(new TypeError('需要数组'));
// TypeError: 需要数组
```

# assert.ifError(value)

value<any>

如果 `value` 不为 `undefined` 或 `null`，则抛出 `value`。 在回调中测试 `error` 参数时，这很有用。 堆栈跟踪包含传递给 `ifError()` 的错误的所有帧，包括 `ifError()` 本身的潜在新帧。

```js
const assert = require('assert').strict;

assert.ifError(null);
// 通过。
assert.ifError(0);
// AssertionError [ERR_ASSERTION]: ifError got unwanted exception: 0
assert.ifError('错误');
// AssertionError [ERR_ASSERTION]: ifError got unwanted exception: '错误'
assert.ifError(new Error());
// AssertionError [ERR_ASSERTION]: ifError got unwanted exception: Error

// 创建一些随机错误帧。
let err;
(function errorFrame() {
  err = new Error('测试错误');
})();

(function ifErrorFrame() {
  assert.ifError(err);
})();
// AssertionError [ERR_ASSERTION]: ifError got unwanted exception: 测试错误
//     at ifErrorFrame
//     at errorFrame
```

# assert.notDeepStrictEqual(actual, expected[, message])

与assert.deepStrictEqual相反，测试深度严格的不平等

# assert.notStrictEqual(actual, expected[, message])

actual <any>

expected <any>

message <string> | <Error>

测试 `actual` 参数和 `expected` 参数之间的严格不相等，使用 [SameValue比较](http://nodejs.cn/s/25ULs2)

```js
const assert = require('assert').strict;

assert.notStrictEqual(1, 2);
// 通过。

assert.notStrictEqual(1, 1);
// AssertionError [ERR_ASSERTION]: Expected "actual" to be strictly unequal to:
//
// 1

assert.notStrictEqual(1, '1');
// 通过。
```

# assert.ok(value[, message])

value <any>

message <string> | <Error>

测试 `value` 是否为真值,如果 `value` 不是真值，则抛出 [`AssertionError`](http://nodejs.cn/s/6wNomq)

```js
const assert = require('assert').strict;

assert.ok(true);
// OK
assert.ok(1);
// OK

assert.ok();
// AssertionError: No value argument passed to `assert.ok()`

assert.ok(false, '这是假值');
// AssertionError: 这是假值

// 在 repl 中：
assert.ok(typeof 123 === 'string');
// AssertionError: false == true

// 在文件中（例如 test.js）：
assert.ok(typeof 123 === 'string');
// AssertionError: The expression evaluated to a falsy value:
//
//   assert.ok(typeof 123 === 'string')

assert.ok(false);
// AssertionError: The expression evaluated to a falsy value:
//
//   assert.ok(false)

assert.ok(0);
// AssertionError: The expression evaluated to a falsy value:
//
//   assert.ok(0)

// 与使用 `assert()` 相同：
assert(0);
// AssertionError: The expression evaluated to a falsy value:
//
//   assert(0)
```

# assert.rejects(asyncFn[, error],[, message])

等待 `asyncFn` Promise，或者，如果 `asyncFn` 是一个函数，则立即调用该函数并等待返回的 Promise 完成。 然后它将检查 Promise 是否被拒绝。

```js
(async () => {
  await assert.rejects(
    async () => {
      throw new TypeError('错误值');
    },
    (err) => {
      assert.strictEqual(err.name, 'TypeError');
      assert.strictEqual(err.message, '错误值');
      return true;
    }
  );
})();
```

# assert.strictEqual(actual, expected[, message])

actual <any>

expected <any>

message <string> | <Error>

试 `actual` 参数和 `expected` 参数之间的严格相等性，使用 [SameValue比较](http://nodejs.cn/s/25ULs2)。

```js
const assert = require('assert').strict;

assert.strictEqual(1, 2);
// AssertionError [ERR_ASSERTION]: Expected inputs to be strictly equal:
//
// 1 !== 2

assert.strictEqual(1, 1);
// OK

assert.strictEqual('Hello foobar', 'Hello World!');
// AssertionError [ERR_ASSERTION]: Expected inputs to be strictly equal:
// + actual - expected
//
// + 'Hello foobar'
// - 'Hello World!'
//          ^

const apples = 1;
const oranges = 2;
assert.strictEqual(apples, oranges, `apples ${apples} !== oranges ${oranges}`);
// AssertionError [ERR_ASSERTION]: apples 1 !== oranges 2

assert.strictEqual(1, '1', new TypeError('Inputs are not identical'));
// TypeError: Inputs are not identical
```

# assert.throws(fn[, error],[, message])

期望fn函数抛出错误。

如果指定，则 `error` 可以是 [`Class`](http://nodejs.cn/s/5wDLcp)、[`RegExp`](http://nodejs.cn/s/tbQJCP)、验证函数，每个属性将被测试严格的深度相等的验证对象、或每个属性（包括不可枚举的 `message` 和 `name` 属性）将被测试严格的深度相等的错误实例。 使用对象时，还可以在对字符串属性进行验证时使用正则表达式。 请参见下面的示例。

如果指定 `message`，则当 `fn` 调用无法抛出或错误验证失败时， `message` 将附加到 `AssertionError` 提供的消息。

由于令人困惑的表示法，建议不要使用字符串作为第二个参数。 这可能会导致难以发现的错误。

```js
const err = new TypeError('错误值');
err.code = 404;
err.foo = 'bar';
err.info = {
  nested: true,
  baz: 'text'
};
err.reg = /abc/i;

assert.throws(
  () => {
    throw err;
  },
  {
    name: 'TypeError',
    message: '错误值',
    info: {
      nested: true,
      baz: 'text'
    }
    // 仅测试验证对象上的属性。
    // 使用嵌套对象需要存在所有属性。
    // 否则验证将失败。
  }
);

// 使用正则表达式验证错误属性：
assert.throws(
  () => {
    throw err;
  },
  {
    // `name` 和 `message` 属性是字符串，使用正则表达式将匹配字符串。 
    // 如果失败，则会抛出错误。
    name: /^TypeError$/,
    message: /错误/,
    foo: 'bar',
    info: {
      nested: true,
      // 无法对嵌套属性使用正则表达式！
      baz: 'text'
    },
    // `reg` 属性包含一个正则表达式，
    // 并且只有当验证对象包含相同的正则表达式时，
    // 它才会通过。
    reg: /abc/i
  }
);

// 由于 `message` 和 `name` 属性不同而失败：
assert.throws(
  () => {
    const otherErr = new Error('未找到');
    // 将所有可枚举的属性从 `err` 拷贝到 `otherErr`。
    for (const [key, value] of Object.entries(err)) {
      otherErr[key] = value;
    }
    throw otherErr;
  },
  // 当使用错误作为验证对象时，也会检查错误的 `message`  和 `name` 属性。
  err
);
```

使用构造函数验证 instanceof

```js
assert.throws(
  () => {
    throw new Error('错误值');
  },
  Error
);
```

使用 [`RegExp`](http://nodejs.cn/s/tbQJCP) 验证错误消息

```js
assert.throws(
  () => {
    throw new Error('错误值');
  },
  /^Error: 错误值$/
);
```

自定义的错误验证函数：

该函数必须返回 `true`，以表明已通过所有的内部验证。 否则它将会失败并带上 [`AssertionError`](http://nodejs.cn/s/6wNomq)

```js
assert.throws(
  () => {
    throw new Error('错误值');
  },
  (err) => {
    assert(err instanceof Error);
    assert(/value/.test(err));
    // 避免从验证函数返回 `true` 以外的任何东西。 
    // 否则，会不清楚验证的哪一部分失败。 
    // 应该抛出有关失败的特定验证的错误（如本例所示），并向该错误添加尽可能多的有用的调试信息。
    return true;
  },
  '不是期望的错误'
);
```

